---
name: Hello
on:
  pull_request:

jobs:
  say-hello:
    name: Basic Hello World
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo "Hello World"
