name: Semantic Release

on:
  push:
    branches:
      - 'release/*'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run test.py
        run: python -m unittest discover s test

      - name: Semantic release
        uses: brpaz/action-semantic-release@v1
